# lets explore the data

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/app_permissions.csv')

In [11]:
df.permission.value_counts()

permission
find accounts on the device                                                         6
modify or delete the contents of your USB storage                                   6
read phone status and identity                                                      6
read the contents of your USB storage                                               6
read your own contact card                                                          3
add or remove accounts                                                              3
directly call phone numbers                                                         3
precise location (GPS and network-based)                                            3
read your contacts                                                                  3
read call log                                                                       3
record audio                                                                        3
take pictures and videos                                                            3
view Wi-Fi connections                                                              3
access Bluetooth settings                                                           3
pair with Bluetooth devices                                                         3
change network connectivity                                                         3
change your audio settings                                                          3
connect and disconnect from Wi-Fi                                                   3
control vibration                                                                   3
create accounts and set passwords                                                   3
full network access                                                                 3
install shortcuts                                                                   3
view network connections                                                            3
prevent device from sleeping                                                        3
reorder running apps                                                                3
run at startup                                                                      3
receive data from Internet                                                          3
add or modify calendar events and send email to guests without owners' knowledge    2
use accounts on the device                                                          2
uninstall shortcuts                                                                 2
capture video output                                                                2
retrieve running apps                                                               2
modify your contacts                                                                2
approximate location (network-based)                                                2
draw over other apps                                                                2
control Near Field Communication                                                    2
read Google service configuration                                                   2
read sync settings                                                                  2
toggle sync on and off                                                              2
send sticky broadcast                                                               2
read calendar events plus confidential information                                  1
read battery statistics                                                             1
download files without notification                                                 1
receive text messages (SMS)                                                         1
send SMS messages                                                                   1
read sync statistics                                                                1
Name: count, dtype: int64

In [9]:
df.loc[df['category'] == 'Contacts']

                   app_id  category                   permission
4   com.instagram.android  Contacts  find accounts on the device
5   com.instagram.android  Contacts           read your contacts
41    com.facebook.katana  Contacts  find accounts on the device
42    com.facebook.katana  Contacts         modify your contacts
43    com.facebook.katana  Contacts           read your contacts
84           com.whatsapp  Contacts  find accounts on the device
85           com.whatsapp  Contacts         modify your contacts
86           com.whatsapp  Contacts           read your contacts

In [8]:
df[df['category'] == 'Other']

                    app_id category                         permission
18   com.instagram.android    Other          access Bluetooth settings
19   com.instagram.android    Other        change network connectivity
20   com.instagram.android    Other         change your audio settings
21   com.instagram.android    Other  connect and disconnect from Wi-Fi
22   com.instagram.android    Other                  control vibration
23   com.instagram.android    Other  create accounts and set passwords
24   com.instagram.android    Other                full network access
25   com.instagram.android    Other                  install shortcuts
26   com.instagram.android    Other        pair with Bluetooth devices
27   com.instagram.android    Other       prevent device from sleeping
28   com.instagram.android    Other               reorder running apps
29   com.instagram.android    Other                     run at startup
30   com.instagram.android    Other                uninstall shortcuts
31   com.instagram.android    Other         use accounts on the device
32   com.instagram.android    Other           view network connections
57     com.facebook.katana    Other          access Bluetooth settings
58     com.facebook.katana    Other        change network connectivity
59     com.facebook.katana    Other         change your audio settings
60     com.facebook.katana    Other  connect and disconnect from Wi-Fi
61     com.facebook.katana    Other   control Near Field Communication
62     com.facebook.katana    Other                  control vibration
63     com.facebook.katana    Other  create accounts and set passwords
64     com.facebook.katana    Other               draw over other apps
65     com.facebook.katana    Other                full network access
66     com.facebook.katana    Other                  install shortcuts
67     com.facebook.katana    Other        pair with Bluetooth devices
68     com.facebook.katana    Other       prevent device from sleeping
69     com.facebook.katana    Other  read Google service configuration
70     com.facebook.katana    Other            read battery statistics
71     com.facebook.katana    Other                 read sync settings
72     com.facebook.katana    Other               reorder running apps
73     com.facebook.katana    Other                     run at startup
74     com.facebook.katana    Other              send sticky broadcast
75     com.facebook.katana    Other             toggle sync on and off
76     com.facebook.katana    Other           view network connections
102           com.whatsapp    Other          access Bluetooth settings
103           com.whatsapp    Other        change network connectivity
104           com.whatsapp    Other         change your audio settings
105           com.whatsapp    Other  connect and disconnect from Wi-Fi
106           com.whatsapp    Other   control Near Field Communication
107           com.whatsapp    Other                  control vibration
108           com.whatsapp    Other  create accounts and set passwords
109           com.whatsapp    Other               draw over other apps
110           com.whatsapp    Other                full network access
111           com.whatsapp    Other                  install shortcuts
112           com.whatsapp    Other        pair with Bluetooth devices
113           com.whatsapp    Other       prevent device from sleeping
114           com.whatsapp    Other  read Google service configuration
115           com.whatsapp    Other                 read sync settings
116           com.whatsapp    Other               reorder running apps
117           com.whatsapp    Other                     run at startup
118           com.whatsapp    Other              send sticky broadcast
119           com.whatsapp    Other             toggle sync on and off
120           com.whatsapp    Other                uninstall shortcuts
121           com.whatsapp    Other         use accounts on the device
122           com.whatsapp    Other           view network connections